/*
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

package app.gyrolet.mpvrx.data.lyrics.providers

import app.gyrolet.mpvrx.domain.lyrics.Lyrics
import app.gyrolet.mpvrx.domain.lyrics.LyricsProvider
import app.gyrolet.mpvrx.domain.lyrics.SyncedLine
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.longOrNull

/**
 * Lyrics tied to the exact video being played: its captions, and the plain
 * text YouTube Music keeps in the video's own Lyrics tab.
 *
 * Both are keyed on the video id rather than on a title, so they can never
 * answer with a different edit. Neither applies to a local file — they return
 * null immediately unless the playing path is a YouTube URL.
 */
internal object YouTubeTranscriptProvider : LyricsProviderClient {
  override val id: LyricsProvider = LyricsProvider.YOUTUBE_TRANSCRIPT

  override suspend fun fetch(query: LyricsFetchQuery): Lyrics? {
    val videoId = query.videoId?.takeIf(SimpMusicProvider.YOUTUBE_ID::matches) ?: return null
    val html = lyricsGet("https://www.youtube.com/watch?v=$videoId&hl=en", BROWSER_HEADERS) ?: return null
    val player = extractPlayerResponse(html) ?: return null
    val tracks = captionTracks(player).filter { it.url.isNotBlank() }.ifEmpty { return null }
    val track = tracks.firstOrNull { !it.autoGenerated } ?: tracks.first()
    val body = lyricsGet("${track.url}&fmt=json3", BROWSER_HEADERS) ?: return null
    return parseCaptions(body)
  }

  /** The player's own JSON blob, which is where the caption tracks live. */
  private fun extractPlayerResponse(html: String): JsonObject? {
    val marker = html.indexOf("ytInitialPlayerResponse")
    if (marker < 0) return null
    val brace = html.indexOf('{', marker)
    if (brace < 0) return null
    var depth = 0
    for (index in brace until html.length) {
      when (html[index]) {
        '{' -> depth++
        '}' -> {
          depth--
          if (depth == 0) {
            val raw = html.substring(brace, index + 1)
            return runCatching { lyricsJson.parseToJsonElement(raw) }.getOrNull() as? JsonObject
          }
        }
      }
    }
    return null
  }

  private fun captionTracks(player: JsonObject): List<CaptionTrack> =
    player
      .objectsNamed("captionTracks")
      .mapNotNull { element ->
        val baseUrl = element.string("baseUrl") ?: return@mapNotNull null
        CaptionTrack(
          url = baseUrl,
          autoGenerated = element.string("kind") == "asr",
        )
      }.toList()

  private fun parseCaptions(body: String): Lyrics? {
    val root = runCatching { lyricsJson.parseToJsonElement(body) }.getOrNull() as? JsonObject ?: return null
    val lines =
      root
        .objectsNamed("events")
        .mapNotNull { event ->
          val start = event["tStartMs"]?.jsonPrimitive?.longOrNull ?: return@mapNotNull null
          val segments = event["segs"] as? JsonArray ?: return@mapNotNull null
          val text =
            segments
              .mapNotNull { (it as? JsonObject)?.string("utf8") }
              .joinToString("")
              .trim(' ', '\n', '♪')
              .takeIf { it.isNotEmpty() } ?: return@mapNotNull null
          SyncedLine(time = start.coerceIn(0, Int.MAX_VALUE.toLong()).toInt(), line = text)
        }.sortedBy { it.time }
        .toList()
    return lyricsFromSynced(lines)
  }
}

internal object YouTubeMusicLyricsProvider : LyricsProviderClient {
  override val id: LyricsProvider = LyricsProvider.YOUTUBE_MUSIC

  private const val KEY = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8"
  private const val NEXT = "https://music.youtube.com/youtubei/v1/next"
  private const val BROWSE = "https://music.youtube.com/youtubei/v1/browse"
  private const val CLIENT_VERSION = "1.20250101.01.00"

  override suspend fun fetch(query: LyricsFetchQuery): Lyrics? {
    val videoId = query.videoId?.takeIf(SimpMusicProvider.YOUTUBE_ID::matches) ?: return null
    val next = postJson(NEXT, clientContext() + ""","videoId":"$videoId"""") ?: return null
    val shelf =
      next
        .objectsNamed("tabRenderer")
        .firstOrNull { tab -> tab.youtubeStrings().any { it.equals("Lyrics", ignoreCase = true) } }
        ?.objectsNamed("browseEndpoint")
        ?.firstOrNull()
        ?: return null
    val browseId = shelf.string("browseId") ?: return null
    val params = shelf.string("params")

    val request =
      buildString {
        append(clientContext())
        append(""","browseId":${quote(browseId)}""")
        if (!params.isNullOrBlank()) append(""","params":${quote(params)}""")
        append('}')
      }
    val browse = postJson(BROWSE, request) ?: return null
    val text =
      browse
        .objectsNamed("musicDescriptionShelfRenderer")
        .firstOrNull()
        ?.let { shelfElement -> shelfElement["description"]?.youtubeStrings()?.joinToString("\n") }
        .orEmpty()
        .trim()
    return lyricsFromPlain(text)
  }

  private fun clientContext(): String =
    """{"context":{"client":{"clientName":"WEB_REMIX","clientVersion":"$CLIENT_VERSION","hl":"en"}}}"""

  private fun quote(value: String): String = "\"" + value.replace("\"", "\\\"") + "\""

  private suspend fun postJson(
    url: String,
    body: String,
  ): JsonObject? {
    val response = lyricsPost(url = "$url?key=$KEY", body = body) ?: return null
    return runCatching { lyricsJson.parseToJsonElement(response) }.getOrNull() as? JsonObject
  }
}

private data class CaptionTrack(
  val url: String,
  /** YouTube labels machine-generated captions "asr"; a human track is better. */
  val autoGenerated: Boolean,
)

private val BROWSER_HEADERS =
  mapOf(
    "User-Agent" to (
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
        "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
    ),
    "Accept-Language" to "en-US,en;q=0.9",
  )

/** Depth-first walk over every object in a document, whatever it is nested under. */
private fun JsonElement?.objectsNamed(name: String): Sequence<JsonObject> =
  sequence {
    when (this@objectsNamed) {
      is JsonObject ->
        for ((key, value) in this@objectsNamed) {
          if (key == name) {
            when (value) {
              is JsonObject -> yield(value)
              is JsonArray -> for (item in value) if (item is JsonObject) yield(item)
              else -> Unit
            }
          }
          yieldAll(value.objectsNamed(name))
        }
      is JsonArray -> for (value in this@objectsNamed) yieldAll(value.objectsNamed(name))
      else -> Unit
    }
  }

private fun JsonElement?.youtubeStrings(): List<String> =
  when (this) {
    is JsonPrimitive -> contentOrNull?.let(::listOf).orEmpty()
    is JsonArray -> flatMap { it.youtubeStrings() }
    is JsonObject -> {
      val direct = string("text") ?: string("simpleText")
      direct?.let(::listOf) ?: values.flatMap { it.youtubeStrings() }
    }
    else -> emptyList()
  }

private fun JsonObject.string(key: String): String? = (this[key] as? JsonPrimitive)?.contentOrNull
